version: '3.8'
services:
  sensei:
    container_name: sensei_prod
    build:
      context: .
      target: development
      dockerfile: Dockerfile.prod
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITLAB_HOST=${GITLAB_HOST}
      - GITLAB_ACCESS_TOKEN=${GITLAB_ACCESS_TOKEN}
      - GITLAB_WEBHOOK_SECRET=${GITLAB_WEBHOOK_SECRET}
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - default
  redis_prod:
    container_name: redis_prod
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: unless-stopped
  redis-sensei-commander:
    container_name: redis-sensei-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8080:8081'
    depends_on:
      - redis
networks:
  default:
    driver: bridge
